# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-02 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('best_host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_of', to='party.Member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.Party'),
        ),
    ]
