# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-06 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='latlng',
            field=models.CharField(default='0.0', max_length=128),
            preserve_default=False,
        ),
    ]
