# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_member_latlng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
